-- =============================================================================
-- 02_CREATE_RAW_TABLES.SQL
-- Creates RAW layer tables (Bronze)
-- =============================================================================

-- Config loaded from 00_env_config.sql
USE DATABASE IDENTIFIER($DB_NAME);
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW.HOURLY_VISITS_RAW (
    SHOPPERTRAK_SITE_ID VARCHAR(50) NOT NULL,
    ORBIT INT,
    INCREMENT_DATE DATE NOT NULL,
    INCREMENT_HOUR NUMBER(38,0) NOT NULL,
    ENTERS NUMBER(38,0) NOT NULL,
    EXITS NUMBER(38,0) NOT NULL,
    _IS_HEALTHY BOOLEAN,
    _LOAD_TS TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE VARCHAR,
    _RAW_HASH VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.SITE_DIM_RAW (
    SHOPPERTRAK_SITE_ID VARCHAR(50) NOT NULL,
    SITE_NAME VARCHAR,
    BOROUGH VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    POSTCODE VARCHAR,
    LAT NUMBER(9,6),
    LON NUMBER(9,6),
    SITE_CATEGORY VARCHAR(50),  -- NEW: Category of site (retail, office, restaurant, etc.)
    SITE_STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- TEST: Site status for CI/CD demo
    _LOAD_TS TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    _RAW_HASH VARCHAR
);

CREATE STREAM IF NOT EXISTS RAW.SITE_DIM_RAW_STREAM 
    ON TABLE RAW.SITE_DIM_RAW 
    APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS RAW.HOURLY_VISITS_RAW_STREAM 
    ON TABLE RAW.HOURLY_VISITS_RAW 
    APPEND_ONLY = TRUE;

SELECT 'RAW tables created for ' || $DB_NAME AS status;
