-- =============================================================================
-- 04_CREATE_PROCEDURES.SQL
-- Creates stored procedures for data processing
-- =============================================================================

SET DB_NAME = '&DB_PREFIX' || '_VISIT_DEMO2_DB';
SET WH_NAME = '&DB_PREFIX' || '_VISIT_DEMO2_WH';
USE DATABASE IDENTIFIER($DB_NAME);

-- Procedure: Merge site dimension data
CREATE OR REPLACE PROCEDURE INT.MERGE_DIM_SITE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    MERGE INTO INT.DIM_SITE t
    USING (
        SELECT * FROM (
            SELECT
                SHOPPERTRAK_SITE_ID, SITE_NAME, BOROUGH, ADDRESS, CITY, STATE, POSTCODE, LAT, LON,
                _LOAD_TS AS _EFFECTIVE_TS, _LOAD_TS, _RAW_HASH,
                ROW_NUMBER() OVER (PARTITION BY SHOPPERTRAK_SITE_ID ORDER BY _LOAD_TS DESC) AS rn
            FROM RAW.SITE_DIM_RAW_STREAM
        ) WHERE rn = 1
    ) s
    ON t.SHOPPERTRAK_SITE_ID = s.SHOPPERTRAK_SITE_ID
    WHEN MATCHED AND t._RAW_HASH <> s._RAW_HASH THEN UPDATE SET
        SITE_NAME = s.SITE_NAME, BOROUGH = s.BOROUGH, ADDRESS = s.ADDRESS,
        CITY = s.CITY, STATE = s.STATE, POSTCODE = s.POSTCODE,
        LAT = s.LAT, LON = s.LON,
        _EFFECTIVE_TS = s._EFFECTIVE_TS, _LOAD_TS = s._LOAD_TS, _RAW_HASH = s._RAW_HASH
    WHEN NOT MATCHED THEN INSERT (
        SHOPPERTRAK_SITE_ID, SITE_NAME, BOROUGH, ADDRESS, CITY, STATE, POSTCODE, LAT, LON,
        _EFFECTIVE_TS, _LOAD_TS, _RAW_HASH
    ) VALUES (
        s.SHOPPERTRAK_SITE_ID, s.SITE_NAME, s.BOROUGH, s.ADDRESS, s.CITY, s.STATE, s.POSTCODE, s.LAT, s.LON,
        s._EFFECTIVE_TS, s._LOAD_TS, s._RAW_HASH
    );
    RETURN 'DIM_SITE merge completed at ' || CURRENT_TIMESTAMP();
END;
$$;

-- Procedure: Merge fact visits data
CREATE OR REPLACE PROCEDURE INT.MERGE_FACT_VISITS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    MERGE INTO INT.FACT_HOURLY_VISITS t
    USING (
        SELECT * FROM (
            SELECT
                SHOPPERTRAK_SITE_ID, ORBIT, INCREMENT_DATE, INCREMENT_HOUR,
                ENTERS::NUMBER(38,0) AS ENTERS,
                LEAST(ENTERS, EXITS)::NUMBER(38,0) AS EXITS,
                (ENTERS - LEAST(ENTERS, EXITS))::NUMBER(38,0) AS NET_VISITS,
                _IS_HEALTHY AS IS_HEALTHY, _LOAD_TS, _RAW_HASH,
                ROW_NUMBER() OVER (
                    PARTITION BY SHOPPERTRAK_SITE_ID, INCREMENT_DATE, INCREMENT_HOUR
                    ORDER BY _LOAD_TS DESC
                ) AS rn
            FROM RAW.HOURLY_VISITS_RAW_STREAM
            WHERE ENTERS >= 0 AND EXITS >= 0 AND INCREMENT_HOUR BETWEEN 0 AND 23
        ) WHERE rn = 1
    ) s
    ON t.SHOPPERTRAK_SITE_ID = s.SHOPPERTRAK_SITE_ID
        AND t.INCREMENT_DATE = s.INCREMENT_DATE
        AND t.INCREMENT_HOUR = s.INCREMENT_HOUR
    WHEN MATCHED AND t._RAW_HASH <> s._RAW_HASH THEN UPDATE SET
        ORBIT = s.ORBIT, ENTERS = s.ENTERS, EXITS = s.EXITS,
        NET_VISITS = s.NET_VISITS, IS_HEALTHY = s.IS_HEALTHY,
        _LOAD_TS = s._LOAD_TS, _RAW_HASH = s._RAW_HASH
    WHEN NOT MATCHED THEN INSERT (
        SHOPPERTRAK_SITE_ID, ORBIT, INCREMENT_DATE, INCREMENT_HOUR,
        ENTERS, EXITS, NET_VISITS, IS_HEALTHY, _LOAD_TS, _RAW_HASH
    ) VALUES (
        s.SHOPPERTRAK_SITE_ID, s.ORBIT, s.INCREMENT_DATE, s.INCREMENT_HOUR,
        s.ENTERS, s.EXITS, s.NET_VISITS, s.IS_HEALTHY, s._LOAD_TS, s._RAW_HASH
    );
    RETURN 'FACT_HOURLY_VISITS merge completed at ' || CURRENT_TIMESTAMP();
END;
$$;

SELECT 'Procedures created for ' || $DB_NAME AS status;
