-- =============================================================================
-- 06_CREATE_VIEWS.SQL
-- Creates presentation layer views (Gold)
-- =============================================================================

-- Config loaded from 00_env_config.sql
USE DATABASE IDENTIFIER($DB_NAME);
USE SCHEMA PRS;

CREATE OR REPLACE VIEW PRS.V_HOURLY_VISITS_ENRICHED AS
SELECT
    f.INCREMENT_DATE,
    f.INCREMENT_HOUR,
    DATEADD('hour', f.INCREMENT_HOUR, f.INCREMENT_DATE::TIMESTAMP_NTZ) AS INCREMENT_TS,
    f.SHOPPERTRAK_SITE_ID,
    s.SITE_NAME,
    s.BOROUGH,
    s.ADDRESS,
    s.CITY,
    s.STATE,
    s.POSTCODE,
    s.LAT,
    s.LON,
    f.ORBIT,
    f.ENTERS,
    f.EXITS,
    f.NET_VISITS,
    f.IS_HEALTHY
FROM INT.FACT_HOURLY_VISITS f
LEFT JOIN INT.DIM_SITE s ON f.SHOPPERTRAK_SITE_ID = s.SHOPPERTRAK_SITE_ID;

CREATE OR REPLACE VIEW PRS.V_DAILY_SITE_VISITS AS
SELECT
    INCREMENT_DATE,
    SHOPPERTRAK_SITE_ID,
    SITE_NAME,
    BOROUGH,
    CITY,
    STATE,
    LAT,
    LON,
    SUM(ENTERS)::int AS ENTERS,
    SUM(EXITS)::int AS EXITS,
    SUM(NET_VISITS)::int AS NET_VISITS,
    AVG(IFF(IS_HEALTHY, 1, 0)) AS HEALTHY_RATE
FROM PRS.V_HOURLY_VISITS_ENRICHED
GROUP BY 1,2,3,4,5,6,7,8;

CREATE OR REPLACE VIEW PRS.V_BOROUGH_SUMMARY AS
SELECT
    BOROUGH,
    INCREMENT_DATE,
    COUNT(DISTINCT SHOPPERTRAK_SITE_ID) AS SITE_COUNT,
    SUM(ENTERS)::int AS TOTAL_ENTERS,
    SUM(EXITS)::int AS TOTAL_EXITS,
    SUM(NET_VISITS)::int AS TOTAL_NET_VISITS,
    AVG(HEALTHY_RATE) AS AVG_HEALTHY_RATE
FROM PRS.V_DAILY_SITE_VISITS
GROUP BY 1, 2;

SELECT 'Views created for ' || $DB_NAME AS status;
